FROM golang:1.23 as builder

WORKDIR /app

RUN go install github.com/pressly/goose/v3/cmd/goose@latest

COPY migrations migrations

CMD GOOSE_DRIVER="postgres" GOOSE_DBSTRING="${PG_DSN}" GOOSE_MIGRATION_DIR="migrations" goose up


